version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    environment:
      - NEXT_PUBLIC_HTTP_URL=http://http-backend:8000
      - NEXT_PUBLIC_SOCKET_URL=ws://ws-backend:8080
      - DATABASE_URL=${DATABASE_URL}
    posrts:
      - "3000:3000"
    depends_on:
      - http-backend
      - ws-backend
    networks:
      - app-network  

  http-backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}  
    ports:
      - "8000:8000"
    depends_on:
      - web
      - ws-backend
    networks:
      - app-network    

  ws-backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.ws
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8080:8080"
    networks:
      - app-network


  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network    


networks:
  app-network:
    driver: bridge      
      
volumes:
  postgres_data:

