FROM node:22-alpine

WORKDIR /apps/web

RUN npm install -g pnpm@9.0.0

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json turbo.json ./

RUN pnpm install

RUN pnpm run db:generate

COPY . .

RUN pnpm run build

EXPOSE 3000

CMD ["pnpm", "run", "start:web"]
